# Generated by Django 4.2.11 on 2024-06-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
