# Generated by Django 4.2.11 on 2024-06-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_post_author_remove_post_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
